djangoson/music/urls.py
from django.conf.urls import url
from . import views

app_name='music'

urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^(?P<album_id>[0-9]+)/$', views.detail, name='detail'),
	url(r'^(?P<album_id>[0-9]+)/favorite/$', views.favorite, name='favorite'),
]

djangoson/website/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
	url(r'^music/', include('music.urls')),
]

djangoson/music/models.py
from django.db import models

class Album(models.Model):
	artist = models.CharField(max_length=250)
	album_title = models.CharField(max_length=250)
	genre = models.CharField(max_length=250)
	album_logo = models.CharField(max_length=1000)
	
	def __str__(self):
		return self.album_title + ' - ' + self.artist
		
class Song(models.Model):
		album = models.ForeignKey(Album, on_delete=models.CASCADE)
		file_type = models.CharField(max_length=10)
		song_title = models.CharField(max_length=250)
		is_favorite = models.BooleanField(default=False)
		
		def __str__(self):
			return self.song_title
		
	
	

djangoson/music/views.py
from django.http import Http404
from django.shortcuts import render, get_object_or_404
from .models import Album, Song

def index(request):
	all_albums = Album.objects.all()
	return render(request, 'music/index.html', {'all_albums': all_albums})

def detail(request, album_id):
	album = get_object_or_404(Album, pk=album_id)
	return render(request, 'music/detail.html', {'album': album})

def favorite(request, album_id):
		album = get_object_or_404(Album, pk=album_id)
		try:
			selected_song = album.song_set.get(pk=request.POST['song'])
		except (KeyError, Song.DoesNotExist):
			return render(request, 'music/detail.html', {
				'album': album,
				'error_message': "You Did not select a valid song",
			})
		else:
			if selected_song.is_favorite:
				selected_song.is_favorite= False
			else:
				selected_song.is_favorite= True
			
			selected_song.save()
			return render(request, 'music/detail.html', {'album': album})

djangoson/music/templates/music/detail.html
<img src="{{album.album_logo}}">
<h1>{{album.album_title}}</h1>
<h2>{{album.artist}}</h2>

{% if error_message %}
	<p><strong>{{ error_message }}</strong></p>
{% endif %}	

<form action="{% url 'music:favorite' album.id %}" method="post">
	{% csrf_token %}
	{% for song in album.song_set.all %}
	<input type="radio" id="song{{ forloop.counter }}" name="song" value="{{ song.id }}"/>
	<label for="song{{ forloop.counter }}">
	{{ song.song_title }}
		{% if song.is_favorite %}
	<img src="https://maxcdn.icons8.com/Share/icon/Messaging//outline_star1600.png" width="20">
	{% endif %}
	</label></br>
	{% endfor %}
	<input type="submit" value="Favorite">
</form>

djangoson/music/templates/music/index.html
{% if all_albums %}
<h3> Here My All Albums:</h3>
<ul>
	{% for album in all_albums %}
	<li><a href="{% url 'music:detail' album.id %}">{{ album.album_title }}</a></li>
	{% endfor %}
</ul>
{% else %}
	<h3>Soory :( No Albums</h3>
{% endif %}	